---
title: "smc++"
author: "Anna Maria Calderon"
date: "2026-04-16"
output: html_document
---

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

# Import Data and Modify

```{r import_data, include=FALSE}

virens <- read.csv("/Users/abc6435/Desktop/KIWA_CONS/data/smc++/virens_plot.csv")

waynei <- read.csv("/Users/abc6435/Desktop/KIWA_CONS/data/smc++/waynei_plot.csv")

btnw <- rbind(virens, waynei)
```

# Plot

```{r plot, include=FALSE}
ggplot(btnw, aes(x = x/1000000, y = y/1000000, color=label)) + 
  geom_line(linewidth=1) +
  scale_color_manual(values=c("#525EFF","red"), labels = c("S.v.virens", "S.v.waynei")) +
  #scale_x_continuous(expand = c(0,0), breaks = seq(0,8,by=1)) +
  scale_y_continuous(breaks=seq(0,2,by=0.25)) +
  ylab(expression("Effective Population "(~italic(N[e])~" in Millions"))) +
  xlab("Years Before Present (Mya)") +
  theme(
    legend.title = element_blank(),
    panel.border = element_rect(color = "black", fill = NA), 
    panel.background = element_blank(), 
    panel.grid.major = element_line(color="lightgray")
  )
```
